/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zuendorf' at '06.06.16 23:54' with Gradle 2.13
 *
 * @author zuendorf, @date 06.06.16 23:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
